### ISSUE TITLE
nbots.io domain registration is expired

### ISSUE THREAD

**Issue by sioulnk** [icebaker/nano-bots#2]
Great project, and really appreciate the ability to integrate ollama direclty into my editor of choice. Was looking to go back through some of the docs on cartridges, and found that all of the links in the GH README go to something at or under `nbots.io`, however as of today that domain is returning an unregistered notice:

![image](https://github.com/icebaker/nano-bots/assets/162158915/b2e6a95f-f3dc-411f-80fa-e753038cf0dd)

**Comment by icebaker** [comment]
Thanks for reporting! It is already fixed, and you should be able to access it now.
